owner: lincbrain
repo: linc-upptime

sites:
  - name: Data portal
    url: https://lincbrain.org
    assignees:
      - kabilar
      - aaronkanzer
  - name: DANDI Hub
    url: https://hub.dandiarchive.org
    assignees:
      - kabilar
      - aaronkanzer
  - name: Documentation
    url: https://docs.lincbrain.org
    assignees:
      - kabilar
  - name: Dashboard
    url: https://dashboard.lincbrain.org
    assignees:
      - kabilar
  # - name: Homepage
  #   url: https://connects.mgh.harvard.edu
  #   assignees:
  #     - kabilar

status-website:
  cname: status.lincbrain.org
  logoUrl: https://raw.githubusercontent.com/lincbrain/linc-artwork/refs/heads/main/linc.logo.color%2Bblack.alpha.notext.png
  name: LINC Status
  introTitle: "Status page of LINC services"
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/lincbrain/linc-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO